FROM recipeyak/base:v3 as builder

# Install Application into container
RUN set -ex && mkdir -p /var/app

WORKDIR /var/app

# Adding dependency files
COPY pyproject.toml pyproject.toml
COPY poetry.lock poetry.lock

# Install our dev dependencies
RUN poetry install

# Install package.json /var/ so we can mount at /app and not have issues with dependences
# http://stackoverflow.com/a/33106611/3555105
COPY package.json /var/
COPY yarn.lock /var/
WORKDIR /var/
RUN yarn install

WORKDIR /var/app
COPY . /var/app

ARG OAUTH_BITBUCKET_CLIENT_ID
ARG OAUTH_FACEBOOK_CLIENT_ID
ARG OAUTH_GITHUB_CLIENT_ID
ARG OAUTH_GITLAB_CLIENT_ID
ARG OAUTH_GOOGLE_CLIENT_ID
ARG FRONTEND_SENTRY_DSN
ARG GIT_SHA

RUN poetry run yak build --web

FROM alpine:3.7
RUN mkdir -p /var/app/build
COPY --from=builder /var/app/frontend/build /var/app/build
COPY --from=builder /var/app/frontend/bootstrap.sh /var/app/
WORKDIR /var/app
