FROM recipeyak/node-puppeteer:latest

RUN mkdir -p /var/app

# Install package.json /var/ so we can mount at /app and not have issues with dependences
# http://stackoverflow.com/a/33106611/3555105
COPY package.json /var/
COPY yarn.lock /var/
WORKDIR /var/
RUN yarn install

# Volume for mounting our local files
WORKDIR /var/app
ENV NODE_PATH=/var/node_modules
VOLUME ["/var/app"]
