FROM node

RUN mkdir -p /var/app

# Install package.json /var/ so we can mount at /app and not have issues with dependences
# http://stackoverflow.com/a/33106611/3555105
COPY package.json /var/
WORKDIR /var/
RUN npm install

WORKDIR /var/app
COPY . /var/app
