FROM node:8.9.4 as builder

RUN mkdir -p /var/app

# Install package.json /var/ so we can mount at /app and not have issues with dependences
# http://stackoverflow.com/a/33106611/3555105
COPY package.json /var/
WORKDIR /var/
RUN npm install

WORKDIR /var/app
COPY . /var/app

ARG OAUTH_BITBUCKET_CLIENT_ID
ARG OAUTH_FACEBOOK_CLIENT_ID
ARG OAUTH_GITHUB_CLIENT_ID
ARG OAUTH_GITLAB_CLIENT_ID
ARG OAUTH_GOOGLE_CLIENT_ID
ARG FRONTEND_SENTRY_DSN

RUN npm run build

FROM alpine:3.7
RUN mkdir -p /var/app/build
COPY --from=builder /var/app/build /var/app/build
COPY --from=builder /var/app/bootstrap.sh /var/app/
WORKDIR /var/app
