#!/usr/bin/env sh
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Pull in environmental variables
source .env

git_rev=$(git rev-parse HEAD)
git_rev_short=$(git rev-parse --short HEAD)

docker build -f $DIR'/frontend/Dockerfile-prod' $DIR'/frontend' \
    --tag recipeyak/react:latest \
    --tag recipeyak/react:${git_rev} \
    --tag recipeyak/react:${git_rev_short} \
    --build-arg OAUTH_BITBUCKET_CLIENT_ID=${OAUTH_BITBUCKET_CLIENT_ID-""} \
    --build-arg OAUTH_FACEBOOK_CLIENT_ID=${OAUTH_FACEBOOK_CLIENT_ID-""} \
    --build-arg OAUTH_GITHUB_CLIENT_ID=${OAUTH_GITHUB_CLIENT_ID-""} \
    --build-arg OAUTH_GITLAB_CLIENT_ID=${OAUTH_GITLAB_CLIENT_ID-""} \
    --build-arg OAUTH_GOOGLE_CLIENT_ID=${OAUTH_GOOGLE_CLIENT_ID-""} \
    --build-arg FRONTEND_SENTRY_DSN=${FRONTEND_SENTRY_DSN}

docker build -f $DIR'/nginx/Dockerfile' $DIR'/nginx' \
    --tag recipeyak/nginx:latest \
    --tag recipeyak/nginx:${git_rev} \
    --tag recipeyak/nginx:${git_rev_short}

docker build -f $DIR'/backend/Dockerfile-prod' $DIR'/backend' \
    --tag recipeyak/django:latest \
    --tag recipeyak/django:${git_rev} \
    --tag recipeyak/django:${git_rev_short}
