#!/usr/bin/env bash
# Restore to recipeyak database using production backup
# usage: ./create <gzipped_backup> <database_name>
# 
# 1. Search for database backup in s3: `aws s3 ls recipeyak-backups`
# 2. Download database: `aws s3 cp s3://recipeyak-backups/2019-02-12T0227Z-db.sql.gz ~/Downloads`
# 3. Restore using this utility: `./create ~/Downloads/2019-02-12T0227Z-db.sql.gz recipeyak`

USAGE='usage: ./create backup.sql.gz recipeyak'

if [[ -z $1 || -z $2 ]]; then
    echo "$USAGE" 1>&2
    exit 1
fi

set -euo pipefail

# Create a new database using with the current time so it's unique
DATE=db$(date -u +"%Y%m%d%H%M%S")
psql -c "Create database $DATE"

# unzip backup and insert into database
gzip -d "$1" -c |  psql -d "$DATE"

# remove recipeyak table if it exists
psql -c 'drop database if exists recipeyak'

# rename our table to recipeyak
psql -c "ALTER DATABASE $DATE rename to recipeyak"
