#!/usr/bin/env sh
set -e

if [ $DOCKER_MACHINE_NAME ]; then
    echo "Disconnecting from existing docker host"
    unset_machine=$(docker-machine env -u)
    eval $unset_machine
fi

if [ -z "$1" ]; then
    echo 'You must specify a docker machine name: ./deploy <machine-name> [tag]' >&2
    exit 1
fi

# catch any errors before running eval
machine_vars=$(docker-machine env $1)
eval $machine_vars

# set tag to argument if provided
if [ "$2" ]; then
    tag=$2
else
    echo "No tag provided. Using 'latest'."
    tag='latest'
fi

echo "Deploying to tag ($tag) to docker machine ($1)"

# pull new files
docker pull recipeyak/nginx:${tag}
docker pull recipeyak/django:${tag}
docker pull recipeyak/react:${tag}

# replace ':latest' with chosen tag
sed -e "s/\:latest/\:${tag}/" docker-compose-deploy.yml > docker-compose-shipit.yml

# update containers
docker-compose -f docker-compose-shipit.yml up --build -d
