#!/usr/bin/env sh
set -e

if [ $DOCKER_MACHINE_NAME ]; then
    echo "Disconnecting from existing docker host"
    unset_machine=$(docker-machine env -u)
    eval $unset_machine
fi

if [ -z "$1" ]; then
    echo 'You must specify a docker machine name: ./maintenance_mode <machine-name> [on|off]' >&2
    exit 1
fi

if [ -z "$2" ]; then
    echo 'You must specify a action (on|off): ./maintenance_mode <machine-name> [on|off]' >&2
    exit 1
fi

# catch any errors before running eval
machine_vars=$(docker-machine env $1)
eval $machine_vars


case $2 in
    on|ON)
        echo "Enabling maintenance mode"
        docker-compose -f docker-compose-shipit.yml exec nginx touch maintenance_on
        echo "Maintenance mode: ON";;
    off|OFF)
        echo "Disabling maintenance mode"
        docker-compose -f docker-compose-shipit.yml exec nginx rm -f maintenance_on
        echo "Maintenance mode: OFF";;
    *) echo "Invalid option. Use arguments 'on' or 'off'.";;
esac
