#!/usr/bin/env sh
set -e

if [ $DOCKER_MACHINE_NAME ]; then
    echo "Disconnecting from existing docker host"
    eval $(docker-machine env -u)
fi

# https://github.com/moby/moby/issues/7336#issuecomment-194310594
docker images | grep --color=none ^recipeyak/ | grep -v '<none>' | awk 'BEGIN{OFS=":"}{print $1,$2}' | xargs -P 4 -I{} docker push {}
