FROM python:3.6.4
ENV PYTHONUNBUFFERD 1

# -- Install Poetry
RUN set -ex && curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python3

# -- Install Application into container:
RUN set -ex && mkdir -p /var/app

WORKDIR /var/app

# -- Adding dependency files
COPY pyproject.toml pyproject.toml
COPY pyproject.lock pyproject.lock

# -- Install dependencies:
RUN set -ex && poetry install

COPY . /var/app
RUN DOCKERBUILD=1 python manage.py collectstatic --noinput

# Inject GIT SHA into settings file to track releases via Sentry
ARG GIT_SHA
RUN sh -c 'sed -i s/\<%=GIT_SHA=%\>/"$GIT_SHA"/ backend/settings.py && grep GIT_SHA backend/settings.py'
