FROM python:3.6.4-slim
ENV PYTHONUNBUFFERD 1

# we need libpq at runtime
# the following can probably be simplified
# -- Install Pipenv:
RUN set -ex && pip install "pipenv~=11.8"

# -- Install Application into container:
RUN set -ex && mkdir -p /var/app

WORKDIR /var/app

# -- Adding Pipfiles
COPY Pipfile Pipfile
COPY Pipfile.lock Pipfile.lock

# -- Install dependencies:
RUN set -ex && pipenv install --dev --deploy --system

COPY . /var/app
RUN DOCKERBUILD=1 python manage.py collectstatic --noinput

# Inject GIT SHA into settings file to track releases via Sentry
ARG GIT_SHA
RUN sh -c 'sed -i s/\<%=GIT_SHA=%\>/"$GIT_SHA"/ backend/settings.py && grep GIT_SHA backend/settings.py'
