import os

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
STORAGE_BUCKET_NAME = os.getenv("STORAGE_BUCKET_NAME", "")
STORAGE_HOSTNAME = os.getenv("STORAGE_HOSTNAME", "")
ABLY_API_KEY = os.getenv("ABLY_API_KEY", "SOME:KEY")
