import os

AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", "")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", "")
STORAGE_BUCKET_NAME = os.getenv("STORAGE_BUCKET_NAME", "")
STORAGE_HOSTNAME = os.getenv("STORAGE_HOSTNAME", "")
ABLY_API_KEY = os.getenv("ABLY_API_KEY", "SOME:KEY")
ALGOLIA_APPLICATION_ID = os.getenv("ALGOLIA_APPLICATION_ID", "")
ALGOLIA_ADMIN_API_KEY = os.getenv("ALGOLIA_ADMIN_API_KEY", "")
ALGOLIA_SEARCH_ONLY_API_KEY = os.getenv("ALGOLIA_SEARCH_ONLY_API_KEY", "")

IMAGE_TRANSFORM_FORMAT = os.getenv("IMAGE_TRANSFORM_FORMAT", "twicpics")
