#!/usr/bin/env bash

cd $(dirname $(dirname "$0"))

# https://docs.djangoproject.com/en/2.0/ref/django-admin/#cmdoption-makemigrations-check
poetry run yak django makemigrations --dry-run --noinput --check > /dev/null
status="$?"
if [[ "$status" != 0 ]]; then
    echo "🚨  Missing migrations"
    exit 1
fi
