#!./.venv/bin/python
# ruff: noqa: T201
import subprocess

from dotenv import load_dotenv
from pydantic_settings import BaseSettings

load_dotenv()


class Config(BaseSettings):
    DATABASE_URL: str


def main() -> None:
    """
    Find unknown categories for shopping list ingredients.
    """
    config = Config()
    find_unknown_categories = """
select
  key
from
  core_shoppinglist s,
  jsonb_each_text((s.ingredients::jsonb ->> 0)::jsonb)
where
  s.created > now() - '6 months'::interval and
  value::jsonb ->> 'category' = 'unknown'
group by 1
order by 1 desc;
"""

    database_exists = subprocess.run(
        (
            "psql",
            config.DATABASE_URL,
            "-c",
            find_unknown_categories,
            "--quiet",
            "--tuples-only",
        ),
        check=True,
        capture_output=True,
    )
    for row in database_exists.stdout.decode().strip().splitlines():
        print(row.strip())


if __name__ == "__main__":
    main()
