#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi
# include "." and find all python files with a shebang
FILES=".";
EXECUTABLE_FILES="$(find . -perm +111 -type f)";
if [ -n "$EXECUTABLE_FILES" ];then
    SHEBANG_FILES=$(grep -E -l '^#!/usr/bin/env python3$' $EXECUTABLE_FILES)
    FILES="$FILES ""$SHEBANG_FILES"
fi
poetry run black $FILES
