#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi

MYPY_ARGS=''
if [[ $CI ]]; then
  mkdir -p backend/reports
  MYPY_ARGS='--junit-xml backend/reports/mypy.xml'
fi

echo 'start mypy'
poetry run mypy --config-file tox.ini $MYPY_ARGS . &

echo 'start flake8'
poetry run flake8 &

echo 'start black'
# black --quiet is too quiet, so we grep for 'would format' in stderr
(poetry run black --check . 2> >( grep 'would reformat')) &

if [[ "$@" == *'--db'* ]]; then
    echo 'check for missing migrations'
    ./s/check_missing_migrations &
else
    echo '--db not passed. Skipping migration check that requires Postgres and Mongo'
fi


echo 'wait for background jobs to execute'
FAIL=0
for job in $(jobs -p)
do
    wait $job || FAIL=1
    echo 'job finished'
done

if [[ $FAIL -gt 0 ]]; then
    echo '🚨  Failure'
else
    echo '✅  Success'
fi

exit $FAIL
