#!/usr/bin/env bash
set -ex
set -o pipefail

format() {
  if [ "$CI" ]; then
    ./.venv/bin/ruff format . --check | awk -v prefix="$PWD" '{print "formatting-violation:" prefix "/" $3 ":formatting required"}'
  else
    ./.venv/bin/ruff format .
  fi
}

ruff() {
 if [ "$CI" ]; then
    ./.venv/bin/ruff . | awk -v prefix="$PWD" '{print prefix "/" $0}'
  else
    ./.venv/bin/ruff . --fix
  fi
}

migrations() {
  if [ "$CI" ]; then
    ./s/check_migrations
  fi
}

typecheck() {
 if [ "$CI" ]; then
    ./s/typecheck | awk -v prefix="$PWD" '{print prefix "/" $0}'
  else
    ./s/typecheck
  fi
}

main() {
  format
  ruff
  migrations
  typecheck
}

main "$@"
