#!/usr/bin/env bash
set -ex

main() {
  export TESTING=1
  export DATABASE_URL=postgres://postgres:postgres@127.0.0.1:5432/postgres
  export DEBUG=1
  export DJANGO_SETTINGS_MODULE="recipeyak.django.settings"

  # shellcheck disable=SC2124
  ARGS="${@}"

  
  # shellcheck disable=SC2086
  if [ "$CI" ]; then
    ./.venv/bin/pytest --tb=line $ARGS
  else
    ./.venv/bin/pytest $ARGS
  fi
}

main "$@"
