#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi

ARGS="$@"
if [[ $ARGS == *'--coverage'* ]]; then
    mkdir -p backend/reports
    ARGS=' --cov-config .coveragerc --cov --junit-xml backend/reports/pytest.xml '"${ARGS/'--coverage'/''}"
fi

# set TESTING so we can disable logging with TestingDisableFilter
export TESTING=1
if [[ "$ARGS" == *'--watch'* ]]; then
    ARGS="${ARGS/'--watch'/''}"
    exec poetry run ptw -- $ARGS
else
    exec poetry run pytest $ARGS
fi

