// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function calendarNextOpen(params: {
  day:
    | "Sunday"
    | "Monday"
    | "Tuesday"
    | "Wednesday"
    | "Thursday"
    | "Friday"
    | "Saturday"
    | "Weekday"
    | "Weekend"
  now: string
}) {
  return http<{
    date: string
  }>({
    url: "/api/v1/calendar/next_open/",
    method: "get",
    params,
  })
}
