// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function calendarCreate(params: { name: string }) {
  return http<{
    id: number
    name: string
  }>({
    url: "/api/v1/calendars/",
    method: "post",
    params,
  })
}
