// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function calendarDelete(params: { calendar_id: number }) {
  return http<{
    id: number
    name: string
  }>({
    url: "/api/v1/calendars/{calendar_id}/",
    method: "delete",
    params,
    pathParamNames: ["calendar_id"],
  })
}
