// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function ingredientCreate(params: {
  quantity: string
  name: string
  description: string
  position?: string | null
  optional?: boolean | null
  recipe_id: number
}) {
  return http<{
    id: number
    quantity: string
    name: string
    description: string
    position: string
    optional: boolean
  }>({
    url: "/api/v1/recipes/{recipe_id}/ingredients/",
    method: "post",
    params,
    pathParamNames: ["recipe_id"],
  })
}
