// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function recipeList() {
  return http<
    Array<{
      id: number
      name: string
      scheduledCount: number
      author: string | null
      tags: Array<string> | null
      ingredients: Array<{
        id: number
        quantity: string
        name: string
      }>
      archived_at: string | null
      primaryImage: {
        id: number
        url: string
        backgroundUrl: string | null
      } | null
    }>
  >({
    url: "/api/v1/recipes/",
    method: "get",
  })
}
