// generated by recipeyak.api.base.codegen
import { http } from "@/apiClient"

export function searchClickCreate(params: {
  query: string
  recipe: {
    id: number
    name: string
    author?: string | null
    tags?: ReadonlyArray<string> | null
    ingredients: ReadonlyArray<{
      id: number
      quantity: string
      name: string
    }>
    archived_at?: string | null
    scheduledCount: number
  }
  matches: ReadonlyArray<{
    kind: string
    value: string
  }>
}) {
  return http<{
    id: number
  }>({
    url: "/api/v1/search-click/",
    method: "post",
    params,
  })
}
