# Generated by Django 1.11.4 on 2017-10-01 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0009_auto_20171001_0602")]

    operations = [
        migrations.AlterField(
            model_name="cartitem",
            name="recipe",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="recipeyak.Recipe"
            ),
        )
    ]
