# Generated by Django 1.11.4 on 2017-10-19 03:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0011_auto_20171001_2129")]

    operations = [
        migrations.RenameField(
            model_name="ingredient", old_name="text", new_name="description"
        ),
        migrations.AddField(
            model_name="ingredient",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ingredient",
            name="unit",
            field=models.CharField(default=1, max_length=255),  # type: ignore [call-overload]
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
