# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0012_auto_20171019_0350")]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="name",
            field=models.CharField(default="default name", max_length=255),
            preserve_default=False,
        )
    ]
