# Generated by Django 1.11.4 on 2017-11-16 19:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0014_auto_20171116_1920")]

    operations = [
        migrations.RenameField(
            model_name="cartitem", old_name="amount", new_name="count"
        )
    ]
