# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0016_auto_20171130_0632")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="servings",
            field=models.CharField(blank=True, max_length=255, null=True),
        )
    ]
