# Generated by Django 1.11.7 on 2017-12-02 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0018_merge_20171202_0538")]

    operations = [
        migrations.RenameField(model_name="recipe", old_name="views", new_name="edits")
    ]
