# Generated by Django 2.0.1 on 2018-01-05 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0021_cartitem_total_cart_additions")]

    operations = [migrations.RemoveField(model_name="recipe", name="cart_additions")]
