# Generated by Django 2.0.2 on 2018-03-03 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0033_membership_is_active")]

    operations = [
        migrations.RemoveField(model_name="invite", name="user"),
        migrations.RemoveField(model_name="user", name="membership"),
        migrations.AddField(
            model_name="membership",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="membership",
            name="level",
            field=models.CharField(
                choices=[
                    ("admin", "admin"),
                    ("member", "member"),
                    ("viewer", "viewer"),
                ],
                default="member",
                max_length=6,
            ),
        ),
    ]
