# Generated by Django 2.0.2 on 2018-03-04 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0035_team_is_public")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="level",
            field=models.CharField(
                choices=[("admin", "admin"), ("member", "member"), ("read", "read")],
                default="member",
                max_length=6,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="membership", unique_together={("user", "team")}
        ),
    ]
