# Generated by Django 2.0.2 on 2018-03-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0040_cartitem")]

    operations = [
        migrations.AlterUniqueTogether(
            name="cartitem", unique_together={("user", "recipe")}
        )
    ]
