# Generated by Django 2.0.2 on 2018-03-24 00:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0041_auto_20180308_2320")]

    operations = [
        migrations.AddField(
            model_name="invite",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
