# Generated by Django 2.0.2 on 2018-03-30 00:57

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0045_invite_status")]

    operations = [
        migrations.RunSQL(
            """
DO $do$
BEGIN
    IF not EXISTS (
            SELECT
                *
            FROM
                pg_extension
            WHERE
                extname = 'citext') THEN
            CREATE EXTENSION "citext";
    END IF;
END $do$""",
            reverse_sql="",
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=django.contrib.postgres.fields.citext.CIEmailField(
                max_length=254, unique=True
            ),
        ),
    ]
