# Generated by Django 2.0.2 on 2018-05-09 01:47

from typing import Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0049_auto_20180505_0104")]

    operations: list[Any] = []
