# Generated by Django 2.0.2 on 2018-05-11 19:55

from typing import Any

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0050_remove_recipe_deleted_at"),
        ("recipeyak", "0049_remove_recipe_deleted_at"),
    ]

    operations: list[Any] = []
