# Generated by Django 2.0.2 on 2018-05-13 00:52

from typing import Any

from django.db import migrations, models


def set_position(apps: Any, schema_editor: Any) -> None:
    """Fill in position for existing records"""
    Ingredient = apps.get_model("recipeyak", "Ingredient")
    db_alias = schema_editor.connection.alias
    for ingredient in Ingredient.objects.using(db_alias).all():
        ingredient.position = ingredient.id
        ingredient.save()


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0052_auto_20180512_0011")]

    operations = [
        migrations.AddField(
            model_name="ingredient",
            name="position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(set_position, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="ingredient", name="position", field=models.FloatField()
        ),
        migrations.AlterUniqueTogether(
            name="step", unique_together={("recipe", "position")}
        ),
        migrations.AlterModelOptions(name="step", options={"ordering": ["-position"]}),
    ]
