# Generated by Django 2.0.2 on 2018-06-23 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0057_scheduledrecipe_team")]

    operations = [
        migrations.AlterField(
            model_name="scheduledrecipe",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        )
    ]
