# Generated by Django 2.2b1 on 2019-03-09 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0067_auto_20190222_2359")]

    operations = [
        migrations.AddConstraint(
            model_name="scheduledrecipe",
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(("team_id", None), ("user_id", None), _negated=True)
                ),
                name="owner_required",
            ),
        )
    ]
