# Generated by Django 2.2 on 2019-10-22 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0069_auto_20190730_0312")]

    operations = [
        migrations.AlterModelOptions(
            name="scheduledrecipe", options={"ordering": ["-on"]}
        )
    ]
