# Generated by Django 2.2 on 2019-11-16 20:29

from typing import Any, List

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0071_note"),
        ("recipeyak", "0071_auto_20191101_0111"),
    ]

    operations: List[Any] = []
