# Generated by Django 2.2 on 2020-02-03 02:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0072_merge_20191116_2029")]

    operations = [
        migrations.CreateModel(
            name="RecipeChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "before",
                    models.CharField(
                        blank=True,
                        help_text="The previous value, sometimes derived from multiple fields",
                        max_length=255,
                    ),
                ),
                (
                    "after",
                    models.CharField(
                        help_text="The new value, sometimes derived from multiple fields",
                        max_length=255,
                    ),
                ),
                (
                    "change_type",
                    models.CharField(
                        choices=[
                            ("NAME", "NAME"),
                            ("AUTHOR", "AUTHOR"),
                            ("SOURCE", "SOURCE"),
                            ("SERVINGS", "SERVINGS"),
                            ("TIME", "TIME"),
                            ("STEP_CREATE", "STEP_CREATE"),
                            ("STEP_UPDATE", "STEP_UPDATE"),
                            ("STEP_DELETE", "STEP_DELETE"),
                            ("INGREDIENT_CREATE", "INGREDIENT_CREATE"),
                            ("INGREDIENT_UPDATE", "INGREDIENT_UPDATE"),
                            ("INGREDIENT_DELETE", "INGREDIENT_DELETE"),
                        ],
                        help_text="The field / model changed.",
                        max_length=255,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        help_text="User who made the change.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={"abstract": False, "db_table": "core_recipechange"},
        )
    ]
