# Generated by Django 2.2 on 2020-02-27 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0074_shoppinglist")]

    operations = [
        migrations.AlterField(
            model_name="recipechange",
            name="after",
            field=models.TextField(
                help_text="The new value, sometimes derived from multiple fields"
            ),
        ),
        migrations.AlterField(
            model_name="recipechange",
            name="before",
            field=models.TextField(
                blank=True,
                help_text="The previous value, sometimes derived from multiple fields",
            ),
        ),
    ]
