# Generated by Django 2.2.12 on 2020-08-01 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0078_auto_20200801_1806")]

    operations = [
        migrations.AlterUniqueTogether(name="step", unique_together=set()),
        migrations.RunSQL(
            """
CREATE UNIQUE INDEX core_step_recipe_id_position_not_deleted_uniq_indx
    ON core_step("recipe_id", "position")
    WHERE "deleted_at" IS NULL;
            """
        ),
    ]
