# Generated by Django 2.2.12 on 2020-08-09 18:40

from typing import Any

from django.db import migrations, models

from recipeyak.models import get_random_ical_id


def forwards_func(apps: Any, schema_editor: Any) -> None:
    """
    Want each team to get their own secret ical id
    """
    Membership = apps.get_model("recipeyak", "Membership")
    db_alias = schema_editor.connection.alias
    for m in Membership.objects.using(db_alias):
        m.calendar_secret_key = get_random_ical_id()
        m.save()


class Migration(migrations.Migration):
    dependencies = [("recipeyak", "0079_auto_20200801_2251")]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="calendar_secret_key",
            field=models.TextField(
                default="", help_text="Secret key used to construct the icalendar url."
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="membership",
            name="calendar_sync_enabled",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, accept requests that have the valid secret key.",
            ),
        ),
        migrations.RunPython(forwards_func, migrations.RunPython.noop),
    ]
