# Generated by Django 2.2.12 on 2020-08-14 17:06

import recipeyak.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("recipeyak", "0080_auto_20200809_1840")]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="calendar_secret_key",
            field=models.TextField(
                default=recipeyak.models.get_random_ical_id,
                help_text="Secret key used to construct the icalendar url.",
            ),
        )
    ]
