# Generated by Django 2.2.12 on 2021-01-30 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0085_merge_20201206_2157"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipechange",
            name="recipe",
            field=models.ForeignKey(
                help_text="Recipe this change is for.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipeyak.Recipe",
            ),
        ),
    ]
