# Generated by Django 2.2.12 on 2021-08-31 20:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0086_recipechange_recipe"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                default=list,
                help_text="Tags for organization recipes.",
                null=True,
                size=None,
            ),
        ),
    ]
