# Generated by Django 2.2.12 on 2021-11-08 03:27

from typing import Any

from django.db import migrations


def backfill(apps: Any, schema_editor: Any) -> None:
    """
    Create TimelineEvents for everything
    """
    db_alias = schema_editor.connection.alias

    Recipe = apps.get_model("recipeyak", "Recipe")
    TimelineEvent = apps.get_model("recipeyak", "TimelineEvent")

    timeline_events = []
    for recipe in Recipe.objects.using(db_alias).all():
        timeline_events.append(
            TimelineEvent(
                action="created", created_by=None, recipe=recipe, created=recipe.created
            )
        )
        if recipe.archived_at:
            timeline_events.append(
                TimelineEvent(
                    action="archived",
                    created_by=None,
                    recipe=recipe,
                    created=recipe.archived_at,
                )
            )
    TimelineEvent.objects.using(db_alias).bulk_create(timeline_events)


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0088_auto_20211108_0327"),
    ]

    operations = [migrations.RunPython(backfill, migrations.RunPython.noop)]
