# Generated by Django 3.2.9 on 2021-12-05 22:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0090_auto_20211118_0304"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="tags",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.TextField(),
                blank=True,
                default=list,
                help_text="Tags for organization recipes.",
                null=True,
                size=None,
            ),
        ),
    ]
