# Generated by Django 3.2.9 on 2022-08-06 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0093_upload"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="note",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="uploads",
                to="recipeyak.note",
            ),
        ),
        migrations.AlterField(
            model_name="upload",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
