# Generated by Django 3.2.9 on 2022-08-20 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0096_auto_20220815_1927"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeView",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("last_visited_at", models.DateTimeField(auto_now=True)),
                ("count", models.IntegerField()),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipeyak.recipe",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "recipe_view",
                "ordering": ["-last_visited_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="recipeview",
            constraint=models.UniqueConstraint(
                fields=("recipe", "user"), name="one_user_view_row_per_recipe"
            ),
        ),
    ]
