# Generated by Django 3.2.9 on 2022-08-30 02:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0097_auto_20220820_2104"),
    ]

    operations = [
        migrations.CreateModel(
            name="Scrape",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("html", models.TextField()),
                ("url", models.TextField()),
                ("duration_sec", models.IntegerField()),
                ("parsed", models.JSONField()),
            ],
            options={
                "db_table": "scrape",
            },
        ),
    ]
