# Generated by Django 3.2.9 on 2022-09-27 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0101_auto_20220925_0220"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="recipe_team",
            new_name="_deprecated_recipe_team",
        ),
    ]
