# Generated by Django 3.2.9 on 2022-11-15 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0102_rename_recipe_team_user__deprecated_recipe_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledrecipe",
            name="created_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
