# Generated by Django 3.2.9 on 2022-12-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0103_scheduledrecipe_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="background_url",
            field=models.TextField(null=True),
        ),
    ]
