# Generated by Django 3.2.9 on 2022-12-19 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipeyak', '0104_upload_background_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='primary_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='recipeyak.upload'),
        ),
        migrations.AddField(
            model_name='upload',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='recipeyak.recipe'),
        ),
    ]
