# Generated by Django 3.2.9 on 2022-12-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0105_auto_20221219_2036"),
        ("recipeyak", "0105_scheduleevent"),
    ]
