# Generated by Django 3.2.9 on 2022-12-21 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0106_merge_0105_auto_20221219_2036_0105_scheduleevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="timelineevent",
            name="upload",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipeyak.upload",
            ),
        ),
    ]
