# Generated by Django 3.2.9 on 2022-12-24 20:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0107_timelineevent_upload"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="scheduledrecipe",
            name="count",
        ),
        migrations.AddField(
            model_name="scheduledrecipe",
            name="_deprecated_count",
            field=models.PositiveIntegerField(
                db_column="count",
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
