# Generated by Django 3.2.9 on 2023-01-01 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("recipeyak", "0111_auto_20230101_1726"),
    ]

    operations = [
        migrations.RunSQL(
            """
update core_recipe
set author = trim(author),
    name = trim(name),
    time = trim(time),
    servings = trim(servings),
    source = trim(source);

update core_step
set text = trim(text);

update core_ingredient
set quantity = trim(quantity),
    name = trim(name),
    description = trim(description);
        """
        )
    ]
