# Generated by Django 3.2.9 on 2023-01-04 04:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0112_trim_whitespace_on_recipes"),
    ]

    operations = [
        migrations.AddField(
            model_name="upload",
            name="scraped_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scrapes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
