# Generated by Django 3.2.9 on 2023-03-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0115_alter_scheduledrecipe_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="dark_mode_enabled",
            new_name="_deprecated_dark_mode_enabled",
        ),
        migrations.AddField(
            model_name="user",
            name="theme",
            field=models.TextField(default="light"),
        ),
        migrations.AlterField(
            model_name="user",
            name="_deprecated_dark_mode_enabled",
            field=models.BooleanField(
                db_column="dark_mode_enabled",
                default=False,
                help_text="frontend darkmode setting",
            ),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.CheckConstraint(
                check=models.Q(("theme__in", ("light", "solarized", "autumn"))),
                name="theme_is_valid",
            ),
        ),
    ]
