# Generated by Django 3.2.9 on 2023-09-22 23:30

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipeyak', '0116_auto_20230302_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeCookChecklistCheck',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('checked', models.BooleanField()),
                ('ingredient', models.ForeignKey(help_text='The related recipe', on_delete=django.db.models.deletion.CASCADE, to='recipeyak.ingredient')),
                ('recipe', models.ForeignKey(help_text='The related recipe', on_delete=django.db.models.deletion.CASCADE, to='recipeyak.recipe')),
            ],
            options={
                'db_table': 'recipe_cook_checklist_check',
            },
        ),
        migrations.AddConstraint(
            model_name='recipecookchecklistcheck',
            constraint=models.UniqueConstraint(fields=('recipe', 'ingredient'), name='recipe_ingredient_uniq'),
        ),
    ]
