# Generated by Django 3.2.9 on 2023-12-17 04:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0118_upload_mime_type"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="user",
            name="theme_is_valid",
        ),
    ]
