# Generated by Django 3.2.9 on 2023-12-18 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeyak', '0119_remove_user_theme_is_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='theme',
            field=models.TextField(db_column='theme', default='light'),
        ),
    ]
