# Generated by Django 3.2.9 on 2023-12-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0121_auto_20231218_1705"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="theme_mode",
            field=models.TextField(default="single"),
        ),
    ]
