# Generated by Django 3.2.9 on 2023-12-27 20:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0122_alter_user_theme_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="SearchClick",
            fields=[
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("content", models.JSONField()),
            ],
            options={
                "db_table": "search_click",
            },
        ),
    ]
