# Generated by Django 3.2.9 on 2023-12-29 17:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0123_searchclick"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="_deprecated_dark_mode_enabled",
        ),
        migrations.RemoveField(
            model_name="user",
            name="_deprecated_recipe_team",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_admin",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
    ]
