# Generated by Django 3.2.9 on 2023-12-29 18:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0124_auto_20231229_1728"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="scheduledrecipe",
            name="owner_required",
        ),
        migrations.RemoveField(
            model_name="ingredient",
            name="_deprecated_position",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cloned_at",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cloned_by",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="cloned_from",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="edits",
        ),
        migrations.RemoveField(
            model_name="recipe",
            name="object_id",
        ),
        migrations.RemoveField(
            model_name="scheduledrecipe",
            name="user",
        ),
        migrations.RemoveField(
            model_name="section",
            name="_deprecated_position",
        ),
        migrations.RemoveField(
            model_name="step",
            name="_deprecated_position",
        ),
        migrations.RemoveField(
            model_name="team",
            name="ical_id",
        ),
        migrations.RemoveField(
            model_name="team",
            name="is_public",
        ),
    ]
