# Generated by Django 3.2.9 on 2024-02-04 02:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0127_auto_20240104_0352"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SearchClick",
        ),
    ]
