# Generated by Django 3.2.9 on 2024-02-13 02:03

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0128_delete_searchclick"),
    ]

    operations = [
        migrations.CreateModel(
            name="NoteHistorical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                (
                    "upload_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(), blank=True, size=None
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipeyak.note"
                    ),
                ),
            ],
            options={
                "db_table": "note_historical",
            },
        ),
    ]
