# Generated by Django 3.2.9 on 2024-03-07 01:25

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0129_notehistorical"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecipeHistorical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("author", models.CharField(blank=True, max_length=255, null=True)),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("time", models.CharField(blank=True, max_length=255, null=True)),
                ("servings", models.CharField(blank=True, max_length=255, null=True)),
                ("archived_at", models.DateTimeField(null=True)),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.TextField(),
                        blank=True,
                        default=list,
                        null=True,
                        size=None,
                    ),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "primary_image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="recipeyak.upload",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipeyak.recipe",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipeyak.team"
                    ),
                ),
            ],
            options={
                "db_table": "recipe_historical",
            },
        ),
        migrations.CreateModel(
            name="StepHistorical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("step_id", models.IntegerField()),
                ("text", models.TextField()),
                ("position", models.TextField()),
                (
                    "recipe_historical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipeyak.recipehistorical",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipeyak.team"
                    ),
                ),
            ],
            options={
                "db_table": "step_historical",
            },
        ),
        migrations.CreateModel(
            name="SectionHistorical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("section_id", models.IntegerField()),
                ("title", models.CharField(max_length=255)),
                ("position", models.TextField()),
                (
                    "recipe_historical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipeyak.recipehistorical",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipeyak.team"
                    ),
                ),
            ],
            options={
                "db_table": "section_historical",
            },
        ),
        migrations.CreateModel(
            name="IngredientHistorical",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(default=django.utils.timezone.now)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("ingredient_id", models.IntegerField()),
                ("quantity", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("position", models.TextField()),
                ("optional", models.BooleanField(default=False)),
                (
                    "recipe_historical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="recipeyak.recipehistorical",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipeyak.team"
                    ),
                ),
            ],
            options={
                "db_table": "ingredient_historical",
            },
        ),
    ]
