# Generated by Django 3.2.9 on 2024-03-07 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "recipeyak",
            "0130_ingredienthistorical_recipehistorical_sectionhistorical_stephistorical",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="notehistorical",
            name="actor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
