# Generated by Django 3.2.9 on 2024-03-07 01:43

from typing import Any

from django.db import migrations, models

from recipeyak.models.user import User
from recipeyak.versioning import save_recipe_version


def _forwards_func(apps: Any, schema_editor: Any) -> None:
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    Recipe = apps.get_model("recipeyak", "Recipe")
    RecipeHistorical = apps.get_model("recipeyak", "RecipeHistorical")
    db_alias = schema_editor.connection.alias
    for recipe in Recipe.objects.using(db_alias).exclude(
        id__in=RecipeHistorical.objects.values("recipe_id")
    ):
        event = recipe.timelineevent_set.filter(action="created").first()
        created_by = event.created_by if event is not None else None
        actor = User.objects.get(id=created_by.id) if created_by is not None else None
        save_recipe_version(recipe_id=recipe.id, actor=actor, created=recipe.created)


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0131_alter_notehistorical_actor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipehistorical",
            name="primary_image",
            field=models.ForeignKey(
                null=True,
                on_delete=models.deletion.PROTECT,
                related_name="+",
                to="recipeyak.upload",
            ),
        ),
        migrations.AlterField(
            model_name="recipehistorical",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.CASCADE, to="recipeyak.team"
            ),
        ),
        migrations.AlterField(
            model_name="ingredienthistorical",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.CASCADE, to="recipeyak.team"
            ),
        ),
        migrations.AlterField(
            model_name="sectionhistorical",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.CASCADE, to="recipeyak.team"
            ),
        ),
        migrations.AlterField(
            model_name="stephistorical",
            name="team",
            field=models.ForeignKey(
                null=True, on_delete=models.deletion.CASCADE, to="recipeyak.team"
            ),
        ),
        migrations.RunPython(_forwards_func),
    ]
