# Generated by Django 3.2.25 on 2025-09-17 02:19

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipeyak', '0135_auto_20240420_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(help_text="Name of calendar, e.g. 'Family Calendar'")),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recipeyak.team')),
            ],
            options={
                'db_table': 'core_calendar',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scheduledrecipe',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='recipeyak.calendar'),
        ),
    ]
