# Generated by Django 3.2.25 on 2025-09-17 02:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0136_calendars"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pinned_calendar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="recipeyak.calendar",
            ),
        ),
    ]
