# Generated by Django 3.2.25 on 2025-09-18 02:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0137_pin_calendar"),
    ]

    operations = [
        migrations.RunSQL("""
insert into core_calendar (id, team_id, name, created, modified)
select
  nextval('core_calendar_id_seq'),
  t.id,
  'Default',
  now(),
  now()
from core_team t
                          """),
        migrations.RunSQL("""
update core_scheduledrecipe
set calendar_id = (
  select id from core_calendar
  where core_calendar.team_id = core_scheduledrecipe.team_id
  order by core_calendar.id asc
  limit 1
)
where calendar_id is null
                          """),
    ]
