# Generated by Django 3.2.25 on 2025-09-18 03:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0138_create_default_calendar"),
    ]

    operations = [
        migrations.RunSQL("""
update core_myuser
set pinned_calendar_id = (
  select id from core_calendar
  where core_calendar.team_id = core_myuser.schedule_team_id
  order by core_calendar.id asc
  limit 1
)
                          """),
    ]
