# Generated by Django 5.2.17 on 2026-08-22 21:12

from django.db import migrations

import recipeyak.models.user


class Migration(migrations.Migration):
    dependencies = [
        ("recipeyak", "0139_create_default_calendar_pins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=recipeyak.models.user.CIEmailField(max_length=254, unique=True),
        ),
    ]
