# Generated by Django 3.2.25 on 2026-09-27 14:28

from django.contrib.postgres.operations import AddIndexConcurrently
from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ("recipeyak", "0139_create_default_calendar_pins"),
    ]

    operations = [
        AddIndexConcurrently(
            model_name="recipe",
            index=models.Index(fields=["team", "-created"], name="recipe_team_created"),
        ),
        AddIndexConcurrently(
            model_name="recipeview",
            index=models.Index(
                fields=["user", "-last_visited_at"],
                name="recipe_view_user_last_visited",
            ),
        ),
        AddIndexConcurrently(
            model_name="scheduledrecipe",
            index=models.Index(
                fields=["calendar", "on"], name="scheduled_recipe_calendar_on"
            ),
        ),
    ]
