from typing import Any, Dict, Optional

from django.contrib.sessions.backends.base import SessionBase

class SessionStore(SessionBase):
    user_agent: str
    ip: str
    user_id: Optional[int]
    def __init__(
        self,
        session_key: Optional[str] = None,
        user_agent: Optional[str] = None,
        ip: Optional[str] = None,
    ) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def load(self) -> Dict[str, Any]: ...
    def exists(self, session_key: str) -> bool: ...
    def create(self) -> None: ...
    def save(self, must_create: bool = False) -> None: ...
    def clear(self) -> None: ...
    def delete(self, session_key: Optional[str] = None) -> None: ...
    @classmethod
    def clear_expired(cls) -> None: ...
