from typing import Any

from django.contrib.sessions.backends.base import SessionBase

class SessionStore(SessionBase):
    user_agent: str
    ip: str
    user_id: int | None
    def __init__(
        self,
        session_key: str | None = None,
        user_agent: str | None = None,
        ip: str | None = None,
    ) -> None: ...
    def __setitem__(self, key: str, value: Any) -> None: ...
    def load(self) -> dict[str, Any]: ...
    def exists(self, session_key: str) -> bool: ...
    def create(self) -> None: ...
    def save(self, must_create: bool = False) -> None: ...
    def clear(self) -> None: ...
    def delete(self, session_key: str | None = None) -> None: ...
    @classmethod
    def clear_expired(cls) -> None: ...
