enum ActionTypes {
  LOG_IN = "LOG_IN",
  SET_LOADING_LOGIN = "SET_LOADING_LOGIN",
  SET_ERROR_LOGIN = "SET_ERROR_LOGIN",

  SET_ERROR_SOCIAL_LOGIN = "SET_ERROR_SOCIAL_LOGIN",

  UPDATE_EMAIL_START = "UPDATE_EMAIL_START",
  UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS",
  UPDATE_EMAIL_FAILURE = "UPDATE_EMAIL_FAILURE",

  SET_TEAM_ID = "SET_TEAM_ID",

  SET_SOCIAL_ACCOUNT_CONNECTIONS = "SET_SOCIAL_ACCOUNT_CONNECTIONS",
  SET_SOCIAL_ACCOUNT_CONNECTION = "SET_SOCIAL_ACCOUNT_CONNECTION",

  FETCH_USER_START = "FETCH_USER_START",
  FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS",
  FETCH_USER_FAILURE = "FETCH_USER_FAILURE",

  TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE",

  SET_LOADING_PASSWORD_UPDATE = "SET_LOADING_PASSWORD_UPDATE",
  SET_ERROR_PASSWORD_UPDATE = "SET_ERROR_PASSWORD_UPDATE",

  SET_LOADING_SIGNUP = "SET_LOADING_SIGNUP",
  SET_ERROR_SIGNUP = "SET_ERROR_SIGNUP",

  SET_LOADING_RESET = "SET_LOADING_RESET",
  SET_ERROR_RESET = "SET_ERROR_RESET",

  SET_LOGGING_OUT = "SET_LOGGING_OUT",

  ADD_RECIPE = "ADD_RECIPE",
  ADD_STEP_TO_RECIPE = "ADD_STEP_TO_RECIPE",
  ADD_INGREDIENT_TO_RECIPE = "ADD_INGREDIENT_TO_RECIPE",
  SET_LOADING_ADD_STEP_TO_RECIPE = "SET_LOADING_ADD_STEP_TO_RECIPE",
  UPDATE_RECIPE_NAME = "UPDATE_RECIPE_NAME",
  UPDATE_RECIPE_SOURCE = "UPDATE_RECIPE_SOURCE",
  UPDATE_RECIPE_AUTHOR = "UPDATE_RECIPE_AUTHOR",
  UPDATE_RECIPE_TIME = "UPDATE_RECIPE_TIME",
  DELETE_INGREDIENT = "DELETE_INGREDIENT",
  UPDATE_INGREDIENT = "UPDATE_INGREDIENT",
  DELETE_STEP = "DELETE_STEP",
  UPDATE_STEP = "UPDATE_STEP",
  SET_LOADING_ADD_RECIPE = "SET_LOADING_ADD_RECIPE",
  SET_ERROR_ADD_RECIPE = "SET_ERROR_ADD_RECIPE",
  DELETE_RECIPE = "DELETE_RECIPE",
  SET_LOADING_RECIPE = "SET_LOADING_RECIPE",
  SET_DELETING_RECIPE = "SET_DELETING_RECIPE",
  SET_RECIPE = "SET_RECIPE",
  SET_ADDING_INGREDIENT_TO_RECIPE = "SET_ADDING_INGREDIENT_TO_RECIPE",
  SET_UPDATING_INGREDIENT = "SET_UPDATING_INGREDIENT",
  SET_REMOVING_INGREDIENT = "SET_REMOVING_INGREDIENT",
  SET_UPDATING_STEP = "SET_UPDATING_STEP",
  SET_REMOVING_STEP = "SET_REMOVING_STEP",
  SET_RECIPE_404 = "SET_RECIPE_404",
  SET_RECIPE_UPDATING = "SET_RECIPE_UPDATING",
  UPDATE_RECIPE_OWNER = "UPDATE_RECIPE_OWNER",

  SET_RECIPES = "SET_RECIPES",
  SET_LOADING_RECIPES = "SET_LOADING_RECIPES",
  SET_ERROR_RECIPES = "SET_ERROR_RECIPES",

  SET_NOTIFICATION = "SET_NOTIFICATION",
  CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION",

  SET_SHOPPING_LIST = "SET_SHOPPING_LIST",
  SET_LOADING_SHOPPING_LIST = "SET_LOADING_SHOPPING_LIST",
  SET_SHOPPING_LIST_ERROR = "SET_SHOPPING_LIST_ERROR",
  SET_SELECTING_START = "SET_SELECTING_START",
  SET_SELECTING_END = "SET_SELECTING_END",

  SET_LOADING_USER_STATS = "SET_LOADING_USER_STATS",
  SET_USER_STATS = "SET_USER_STATS",

  SET_LOADING_RESET_CONFIRMATION = "SET_LOADING_RESET_CONFIRMATION",
  SET_ERROR_RESET_CONFIRMATION = "SET_ERROR_RESET_CONFIRMATION",

  SET_ADD_RECIPE_FORM_NAME = "SET_ADD_RECIPE_FORM_NAME",
  SET_ADD_RECIPE_FORM_AUTHOR = "SET_ADD_RECIPE_FORM_AUTHOR",
  SET_ADD_RECIPE_FORM_SOURCE = "SET_ADD_RECIPE_FORM_SOURCE",
  SET_ADD_RECIPE_FORM_TIME = "SET_ADD_RECIPE_FORM_TIME",
  SET_ADD_RECIPE_FORM_SERVINGS = "SET_ADD_RECIPE_FORM_SERVINGS",
  SET_ADD_RECIPE_FORM_TEAM = "SET_ADD_RECIPE_FORM_TEAM",
  ADD_ADD_RECIPE_FORM_INGREDIENT = "ADD_ADD_RECIPE_FORM_INGREDIENT",
  REMOVE_ADD_RECIPE_FORM_INGREDIENT = "REMOVE_ADD_RECIPE_FORM_INGREDIENT",
  ADD_ADD_RECIPE_FORM_STEP = "ADD_ADD_RECIPE_FORM_STEP",
  REMOVE_ADD_RECIPE_FORM_STEP = "REMOVE_ADD_RECIPE_FORM_STEP",
  UPDATE_ADD_RECIPE_FORM_INGREDIENT = "UPDATE_ADD_RECIPE_FORM_INGREDIENT",
  UPDATE_ADD_RECIPE_FORM_STEP = "UPDATE_ADD_RECIPE_FORM_STEP",
  CLEAR_ADD_RECIPE_FORM = "CLEAR_ADD_RECIPE_FORM",

  SET_FROM_URL = "SET_FROM_URL",

  ADD_TEAM = "ADD_TEAM",
  DELETE_TEAM = "DELETE_TEAM",
  SET_LOADING_TEAM = "SET_LOADING_TEAM",
  SET_LOADING_TEAM_MEMBERS = "SET_LOADING_TEAM_MEMBERS",
  SET_LOADING_TEAM_INVITES = "SET_LOADING_TEAM_INVITES",
  SET_TEAM_404 = "SET_TEAM_404",
  SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS",
  SET_TEAM_INVITES = "SET_TEAM_INVITES",
  SET_TEAM_RECIPES = "SET_TEAM_RECIPES",
  SET_LOADING_TEAM_RECIPES = "SET_LOADING_TEAM_RECIPES",
  SET_UPDATING_USER_TEAM_LEVEL = "SET_UPDATING_USER_TEAM_LEVEL",
  SET_UPDATING_MEMBERSHIP = "SET_UPDATING_MEMBERSHIP",
  SET_USER_TEAM_LEVEL = "SET_USER_TEAM_LEVEL",
  SET_DELETING_MEMBERSHIP = "SET_DELETING_MEMBERSHIP",
  DELETE_MEMBERSHIP = "DELETE_MEMBERSHIP",
  SET_SENDING_TEAM_INVITES = "SET_SENDING_TEAM_INVITES",
  SET_TEAMS = "SET_TEAMS",
  SET_TEAM = "SET_TEAM",
  SET_CREATING_TEAM = "SET_CREATING_TEAM",
  UPDATE_TEAM = "UPDATE_TEAM",

  SET_LOADING_TEAMS = "SET_LOADING_TEAMS",

  SET_COPYING_TEAM = "SET_COPYING_TEAM",
  SET_MOVING_TEAM = "SET_MOVING_TEAM",

  SET_INVITES = "SET_INVITES",
  SET_LOADING_INVITES = "SET_LOADING_INVITES",
  SET_ERROR_FETCHING_INVITES = "SET_ERROR_FETCHING_INVITES",
  SET_DECLINING_INVITE = "SET_DECLINING_INVITE",
  SET_ACCEPTING_INVITE = "SET_ACCEPTING_INVITE",
  SET_DECLINED_INVITE = "SET_DECLINED_INVITE",
  SET_ACCEPTED_INVITE = "SET_ACCEPTED_INVITE",

  SET_CALENDAR_RECIPES = "SET_CALENDAR_RECIPES",
  SET_CALENDAR_RECIPE = "SET_CALENDAR_RECIPE",
  DELETE_CALENDAR_RECIPE = "DELETE_CALENDAR_RECIPE",
  SET_CALENDAR_ERROR = "SET_CALENDAR_ERROR",
  SET_CALENDAR_LOADING = "SET_CALENDAR_LOADING",
  SET_SCHEDULING_RECIPE = "SET_SCHEDULING_RECIPE",
  MOVE_CALENDAR_RECIPE = "MOVE_CALENDAR_RECIPE",
  REPLACE_CALENDAR_RECIPE = "REPLACE_CALENDAR_RECIPE",

  SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN",

  SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS",
  CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS",
  INCR_LOADING_SEARCH = "INCR_LOADING_SEARCH",
  DECR_LOADING_SEARCH = "DECR_LOADING_SEARCH"
}

export default ActionTypes
