export const LOG_IN = 'LOG_IN'
export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN'
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN'

export const LOG_OUT = 'LOG_OUT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ADD_RECIPE = 'ADD_RECIPE'
export const REMOVE_RECIPE = 'REMOVE_RECIPE'
export const ADD_STEP_TO_RECIPE = 'ADD_STEP_TO_RECIPE'
export const ADD_INGREDIENT_TO_RECIPE = 'ADD_INGREDIENT_TO_RECIPE'
export const UPDATE_RECIPE_NAME = 'UPDATE_RECIPE_NAME'
export const UPDATE_RECIPE_SOURCE = 'UPDATE_RECIPE_SOURCE'
export const UPDATE_RECIPE_AUTHOR = 'UPDATE_RECIPE_AUTHOR'
export const UPDATE_RECIPE_TIME = 'UPDATE_RECIPE_TIME'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const DELETE_STEP = 'DELETE_STEP'
