export const LOG_IN = "LOG_IN"
export const SET_ERROR_LOGIN = "SET_ERROR_LOGIN"

export const SET_ERROR_SOCIAL_LOGIN = "SET_ERROR_SOCIAL_LOGIN"

export const UPDATE_EMAIL_START = "UPDATE_EMAIL_START"
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS"
export const UPDATE_EMAIL_FAILURE = "UPDATE_EMAIL_FAILURE"

export const SET_TEAM_ID = "SET_TEAM_ID"

export const SET_SOCIAL_ACCOUNT_CONNECTIONS = "SET_SOCIAL_ACCOUNT_CONNECTIONS"
export const SET_SOCIAL_ACCOUNT_CONNECTION = "SET_SOCIAL_ACCOUNT_CONNECTION"

export const FETCH_USER_START = "FETCH_USER_START"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE"

export const SET_LOADING_PASSWORD_UPDATE = "SET_LOADING_PASSWORD_UPDATE"
export const SET_ERROR_PASSWORD_UPDATE = "SET_ERROR_PASSWORD_UPDATE"

export const SET_ERROR_SIGNUP = "SET_ERROR_SIGNUP"

export const SET_ERROR_RESET = "SET_ERROR_RESET"

export const SET_LOGGING_OUT = "SET_LOGGING_OUT"

export const ADD_RECIPE = "ADD_RECIPE"
export const ADD_STEP_TO_RECIPE = "ADD_STEP_TO_RECIPE"
export const ADD_INGREDIENT_TO_RECIPE = "ADD_INGREDIENT_TO_RECIPE"
export const SET_LOADING_ADD_STEP_TO_RECIPE = "SET_LOADING_ADD_STEP_TO_RECIPE"
export const UPDATE_RECIPE_NAME = "UPDATE_RECIPE_NAME"
export const UPDATE_RECIPE_SOURCE = "UPDATE_RECIPE_SOURCE"
export const UPDATE_RECIPE_AUTHOR = "UPDATE_RECIPE_AUTHOR"
export const UPDATE_RECIPE_TIME = "UPDATE_RECIPE_TIME"
export const DELETE_INGREDIENT = "DELETE_INGREDIENT"
export const UPDATE_INGREDIENT = "UPDATE_INGREDIENT"
export const DELETE_STEP = "DELETE_STEP"
export const UPDATE_STEP = "UPDATE_STEP"
export const SET_ERROR_ADD_RECIPE = "SET_ERROR_ADD_RECIPE"
export const DELETE_RECIPE = "DELETE_RECIPE"
export const SET_LOADING_RECIPE = "SET_LOADING_RECIPE"
export const SET_DELETING_RECIPE = "SET_DELETING_RECIPE"
export const SET_RECIPE = "SET_RECIPE"
export const SET_ADDING_INGREDIENT_TO_RECIPE = "SET_ADDING_INGREDIENT_TO_RECIPE"
export const SET_UPDATING_INGREDIENT = "SET_UPDATING_INGREDIENT"
export const SET_REMOVING_INGREDIENT = "SET_REMOVING_INGREDIENT"
export const SET_UPDATING_STEP = "SET_UPDATING_STEP"
export const SET_REMOVING_STEP = "SET_REMOVING_STEP"
export const SET_RECIPE_404 = "SET_RECIPE_404"
export const SET_RECIPE_UPDATING = "SET_RECIPE_UPDATING"
export const UPDATE_RECIPE_OWNER = "UPDATE_RECIPE_OWNER"

export const SET_RECIPES = "SET_RECIPES"
export const SET_ERROR_RECIPES = "SET_ERROR_RECIPES"

export const SET_NOTIFICATION = "SET_NOTIFICATION"
export const CLEAR_NOTIFICATION = "CLEAR_NOTIFICATION"

export const SET_SHOPPING_LIST = "SET_SHOPPING_LIST"
export const SET_LOADING_SHOPPING_LIST = "SET_LOADING_SHOPPING_LIST"
export const SET_SHOPPING_LIST_ERROR = "SET_SHOPPING_LIST_ERROR"
export const SET_SELECTING_START = "SET_SELECTING_START"
export const SET_SELECTING_END = "SET_SELECTING_END"

export const SET_LOADING_USER_STATS = "SET_LOADING_USER_STATS"
export const SET_USER_STATS = "SET_USER_STATS"

export const SET_ERROR_RESET_CONFIRMATION = "SET_ERROR_RESET_CONFIRMATION"

export const SET_ADD_RECIPE_FORM_NAME = "SET_ADD_RECIPE_FORM_NAME"
export const SET_ADD_RECIPE_FORM_AUTHOR = "SET_ADD_RECIPE_FORM_AUTHOR"
export const SET_ADD_RECIPE_FORM_SOURCE = "SET_ADD_RECIPE_FORM_SOURCE"
export const SET_ADD_RECIPE_FORM_TIME = "SET_ADD_RECIPE_FORM_TIME"
export const SET_ADD_RECIPE_FORM_SERVINGS = "SET_ADD_RECIPE_FORM_SERVINGS"
export const SET_ADD_RECIPE_FORM_TEAM = "SET_ADD_RECIPE_FORM_TEAM"
export const ADD_ADD_RECIPE_FORM_INGREDIENT = "ADD_ADD_RECIPE_FORM_INGREDIENT"
export const REMOVE_ADD_RECIPE_FORM_INGREDIENT =
  "REMOVE_ADD_RECIPE_FORM_INGREDIENT"
export const ADD_ADD_RECIPE_FORM_STEP = "ADD_ADD_RECIPE_FORM_STEP"
export const REMOVE_ADD_RECIPE_FORM_STEP = "REMOVE_ADD_RECIPE_FORM_STEP"
export const UPDATE_ADD_RECIPE_FORM_INGREDIENT =
  "UPDATE_ADD_RECIPE_FORM_INGREDIENT"
export const UPDATE_ADD_RECIPE_FORM_STEP = "UPDATE_ADD_RECIPE_FORM_STEP"
export const CLEAR_ADD_RECIPE_FORM = "CLEAR_ADD_RECIPE_FORM"

export const SET_FROM_URL = "SET_FROM_URL"

export const ADD_TEAM = "ADD_TEAM"
export const DELETE_TEAM = "DELETE_TEAM"
export const SET_LOADING_TEAM = "SET_LOADING_TEAM"
export const SET_LOADING_TEAM_MEMBERS = "SET_LOADING_TEAM_MEMBERS"
export const SET_LOADING_TEAM_INVITES = "SET_LOADING_TEAM_INVITES"
export const SET_TEAM_404 = "SET_TEAM_404"
export const SET_TEAM_MEMBERS = "SET_TEAM_MEMBERS"
export const SET_TEAM_INVITES = "SET_TEAM_INVITES"
export const SET_TEAM_RECIPES = "SET_TEAM_RECIPES"
export const SET_LOADING_TEAM_RECIPES = "SET_LOADING_TEAM_RECIPES"
export const SET_UPDATING_USER_TEAM_LEVEL = "SET_UPDATING_USER_TEAM_LEVEL"
export const SET_UPDATING_MEMBERSHIP = "SET_UPDATING_MEMBERSHIP"
export const SET_USER_TEAM_LEVEL = "SET_USER_TEAM_LEVEL"
export const SET_DELETING_MEMBERSHIP = "SET_DELETING_MEMBERSHIP"
export const DELETE_MEMBERSHIP = "DELETE_MEMBERSHIP"
export const SET_SENDING_TEAM_INVITES = "SET_SENDING_TEAM_INVITES"
export const SET_TEAMS = "SET_TEAMS"
export const SET_TEAM = "SET_TEAM"
export const SET_CREATING_TEAM = "SET_CREATING_TEAM"
export const UPDATE_TEAM = "UPDATE_TEAM"

export const SET_LOADING_TEAMS = "SET_LOADING_TEAMS"

export const SET_COPYING_TEAM = "SET_COPYING_TEAM"
export const SET_MOVING_TEAM = "SET_MOVING_TEAM"

export const SET_INVITES = "SET_INVITES"
export const SET_LOADING_INVITES = "SET_LOADING_INVITES"
export const SET_ERROR_FETCHING_INVITES = "SET_ERROR_FETCHING_INVITES"
export const SET_DECLINING_INVITE = "SET_DECLINING_INVITE"
export const SET_ACCEPTING_INVITE = "SET_ACCEPTING_INVITE"
export const SET_DECLINED_INVITE = "SET_DECLINED_INVITE"
export const SET_ACCEPTED_INVITE = "SET_ACCEPTED_INVITE"

export const SET_CALENDAR_RECIPES = "SET_CALENDAR_RECIPES"
export const SET_CALENDAR_RECIPE = "SET_CALENDAR_RECIPE"
export const DELETE_CALENDAR_RECIPE = "DELETE_CALENDAR_RECIPE"
export const SET_CALENDAR_ERROR = "SET_CALENDAR_ERROR"
export const SET_CALENDAR_LOADING = "SET_CALENDAR_LOADING"
export const SET_SCHEDULING_RECIPE = "SET_SCHEDULING_RECIPE"
export const MOVE_CALENDAR_RECIPE = "MOVE_CALENDAR_RECIPE"
export const REPLACE_CALENDAR_RECIPE = "REPLACE_CALENDAR_RECIPE"

export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN"

export const SET_SEARCH_RESULTS = "SET_SEARCH_RESULTS"
export const CLEAR_SEARCH_RESULTS = "CLEAR_SEARCH_RESULTS"
export const INCR_LOADING_SEARCH = "INCR_LOADING_SEARCH"
export const DECR_LOADING_SEARCH = "DECR_LOADING_SEARCH"
