export const LOG_IN = 'LOG_IN'
export const SET_LOADING_LOGIN = 'SET_LOADING_LOGIN'
export const SET_ERROR_LOGIN = 'SET_ERROR_LOGIN'

export const SET_LOADING_SIGNUP = 'SET_LOADING_SIGNUP'
export const SET_ERROR_SIGNUP = 'SET_ERROR_SIGNUP'

export const SET_LOADING_RESET = 'SET_LOADING_RESET'
export const SET_ERROR_RESET = 'SET_ERROR_RESET'

export const LOG_OUT = 'LOG_OUT'

export const ADD_TO_CART = 'ADD_TO_CART'
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const ADD_RECIPE = 'ADD_RECIPE'
export const REMOVE_RECIPE = 'REMOVE_RECIPE'
export const ADD_STEP_TO_RECIPE = 'ADD_STEP_TO_RECIPE'
export const ADD_INGREDIENT_TO_RECIPE = 'ADD_INGREDIENT_TO_RECIPE'
export const UPDATE_RECIPE_NAME = 'UPDATE_RECIPE_NAME'
export const UPDATE_RECIPE_SOURCE = 'UPDATE_RECIPE_SOURCE'
export const UPDATE_RECIPE_AUTHOR = 'UPDATE_RECIPE_AUTHOR'
export const UPDATE_RECIPE_TIME = 'UPDATE_RECIPE_TIME'
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT'
export const DELETE_STEP = 'DELETE_STEP'
export const SET_RECIPES = 'SET_RECIPES'
export const SET_LOADING_RECIPES = 'SET_LOADING_RECIPES'
export const SET_LOADING_ADD_RECIPE = 'SET_LOADING_ADD_RECIPE'

export const SET_NOTIFICATION = 'SET_NOTIFICATION'
export const CLEAR_NOTIFICATION = 'CLEAR_NOTIFICATION'
