export const LOG_IN = "LOG_IN"


export const UPDATE_EMAIL_START = "UPDATE_EMAIL_START"
export const UPDATE_EMAIL_SUCCESS = "UPDATE_EMAIL_SUCCESS"
export const UPDATE_EMAIL_FAILURE = "UPDATE_EMAIL_FAILURE"

export const SET_TEAM_ID = "SET_TEAM_ID"

export const SET_SOCIAL_ACCOUNT_CONNECTIONS = "SET_SOCIAL_ACCOUNT_CONNECTIONS"
export const SET_SOCIAL_ACCOUNT_CONNECTION = "SET_SOCIAL_ACCOUNT_CONNECTION"


export const FETCH_USER_START = "FETCH_USER_START"
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS"
export const FETCH_USER_FAILURE = "FETCH_USER_FAILURE"

export const TOGGLE_DARK_MODE = "TOGGLE_DARK_MODE"



export const SET_LOGGING_OUT = "SET_LOGGING_OUT"



export const SET_LOADING_USER_STATS = "SET_LOADING_USER_STATS"
export const SET_USER_STATS = "SET_USER_STATS"







export const SET_USER_LOGGED_IN = "SET_USER_LOGGED_IN"
