#!/usr/bin/env sh
set -e

if [ $DOCKER_MACHINE_NAME ]; then
    echo "Disconnecting from existing docker host"
    unset_machine=$(docker-machine env -u)
    eval $unset_machine
fi

if [ -z "$1" ]; then
    echo 'You must specify a docker machine name: ./connect <machine-name>' >&2
    exit 1
fi

# catch any errors before running eval
machine_vars=$(docker-machine env $1)
eval $machine_vars

exec docker-machine ssh $1
