#!/usr/bin/env bash
# Run commands with variables sourced from the top level .env file.
set -e

cd $(dirname $(dirname "$0"))

if [[ -f .env ]]; then
    # export all variables from env file
    set -a
    source .env
    set +a
fi

exec "$@"
