#!/usr/bin/env python3

import os
import sys
from pathlib import Path
from typing import NoReturn

from utils import run_all


def main() -> NoReturn:
    is_fix = os.getenv("CI") is None
    cmds = {
        "black": ["./.venv/bin/black", "."],
        "prettier": [
            "./node_modules/.bin/prettier",
            "**/*.{js,jsx,scss,css,ts,tsx,json,yaml,yml,md}",
        ],
    }

    if is_fix:
        cmds["prettier"].append("--write")
    else:
        cmds["prettier"].append("--list-different")
        cmds["black"].append("--check")

    os.chdir(Path(__file__).parent.parent)
    exit_code = run_all(cmds=cmds)
    sys.exit(exit_code)


if __name__ == "__main__":
    main()
