#!/usr/bin/env bash

echo "CIRCLE_BRANCH" "$CIRCLE_BRANCH"
echo "CIRCLE_BUILD_NUM" "$CIRCLE_BUILD_NUM"
echo "CIRCLE_BUILD_URL" "$CIRCLE_BUILD_URL"
echo "CIRCLE_COMPARE_URL" "$CIRCLE_COMPARE_URL"
echo "CIRCLE_INTERNAL_TASK_DATA" "$CIRCLE_INTERNAL_TASK_DATA"
echo "CIRCLE_JOB" "$CIRCLE_JOB"
echo "CIRCLE_NODE_INDEX" "$CIRCLE_NODE_INDEX"
echo "CIRCLE_NODE_TOTAL" "$CIRCLE_NODE_TOTAL"
echo "CIRCLE_PR_NUMBER" "$CIRCLE_PR_NUMBER"
echo "CIRCLE_PR_REPONAME" "$CIRCLE_PR_REPONAME"
echo "CIRCLE_PR_USERNAME" "$CIRCLE_PR_USERNAME"
echo "CIRCLE_PREVIOUS_BUILD_NUM" "$CIRCLE_PREVIOUS_BUILD_NUM"
echo "CIRCLE_PROJECT_REPONAME" "$CIRCLE_PROJECT_REPONAME"
echo "CIRCLE_PROJECT_USERNAME" "$CIRCLE_PROJECT_USERNAME"
echo "CIRCLE_PULL_REQUEST" "$CIRCLE_PULL_REQUEST"
echo "CIRCLE_PULL_REQUESTS" "$CIRCLE_PULL_REQUESTS"
echo "CIRCLE_REPOSITORY_URL" "$CIRCLE_REPOSITORY_URL"
echo "CIRCLE_SHA1" "$CIRCLE_SHA1"
echo "CIRCLE_TAG" "$CIRCLE_TAG"
echo "CIRCLE_USERNAME" "$CIRCLE_USERNAME"
echo "CIRCLE_WORKFLOW_ID" "$CIRCLE_WORKFLOW_ID"
echo "CIRCLE_WORKING_DIRECTORY" "$CIRCLE_WORKING_DIRECTORY"
echo "CIRCLECI" "$CIRCLECI"
echo "HOME" "$HOME"

echo "git rev-parse master"
git rev-parse master
echo "git rev-parse FETCH_HEAD"
git rev-parse FETCH_HEAD
echo "git rev-parse head"
git rev-parse head
echo "git merge-base FETCH_HEAD master"
git merge-base FETCH_HEAD master

echo "diff list with merge-base"
git --no-pager diff --name-only FETCH_HEAD $(git merge-base FETCH_HEAD master)

echo "diff list against FETCH_HEAD"
git --no-pager diff --name-only FETCH_HEAD


git branch -f master origin/master

echo "parse revs"
git rev-parse master
git rev-parse FETCH_HEAD
git rev-parse head
