#!/usr/bin/env python3
import os
import subprocess
from shutil import which
import logging

logging.basicConfig(level=logging.INFO)
log = logging.getLogger(__file__)


def is_installed(name: str) -> bool:
    return which(name) is not None


def main() -> None:
    # circle's built in git checkout code clobbers the `master` ref so we do the
    # following to make it not point to the current ref.
    # https://discuss.circleci.com/t/git-checkout-of-a-branch-destroys-local-reference-to-master/23781/7
    if os.getenv("CIRCLECI"):
        subprocess.run(["git", "branch", "-f", "master", "origin/master"], check=True)

    if not is_installed("squawk"):
        subprocess.run(["npm", "config", "set", "unsafe-perm", "true"], check=True)
        log.info("squawk not found, installing")
        subprocess.run(["npm", "install", "-g", "squawk-cli@0.1.4"], check=True)

    changed_migration_files = str(
        subprocess.run(
            [
                "git",
                "--no-pager",
                "diff",
                "--name-only",
                "FETCH_HEAD",
                "master",
                "./backend/core/migrations",
            ],
            capture_output=True,
            check=True,
        )
    )

    changed_migration_files_v2 = str(
        subprocess.run(
            [
                "git",
                "--no-pager",
                "diff",
                "--name-only",
                "master..",
                "./backend/core/migrations",
            ],
            capture_output=True,
            check=True,
        )
    )
    log.info(changed_migration_files)
    log.info(changed_migration_files_v2)


if __name__ == "__main__":
    main()
