#!/bin/bash

set -e

dir_changed() {
  # when the script fails in an unexpected way we default to exit code 0 so
  # that the dir will be considered changed.
  local -r dir="${1}" || exit 0
  local changed_files
  changed_files="$(git --no-pager diff --name-only FETCH_HEAD master)" || exit 0
  grep -q "^${dir}" <<< "${changed_files}"
}

main() {
  # circle's built in git checkout code clobbers the `master` ref so we do the
  # following to make it not point to the current ref.
  # https://discuss.circleci.com/t/git-checkout-of-a-branch-destroys-local-reference-to-master/23781/7
  if [ "${CIRCLECI}" ]; then
    git branch -f master origin/master
  fi

  if ! command -v squawk &>/dev/null; then
    # allow root to install squawk globally
    npm config set unsafe-perm true
    echo "squawk not found, installing"
    npm i -g squawk-cli@0.1.4
  fi

  local changed_files

  changed_files=$(git --no-pager diff --name-only FETCH_HEAD master)

  echo $changed_files


  local changed_migration_files

  changed_migration_files=$(git --no-pager diff --name-only FETCH_HEAD master ./backend/core/migrations)

  echo $changed_migration_files

  if dir_changed "backend/core/migrations"; then
    echo "dir changed"
  fi

  squawk example.sql
}

main "${@}"
