#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f .env ]]; then
    # export all variables from env file
    set -a
    source .env
    set +a
fi

cd backend

ARGS="$@"
# set TESTING so we can disable logging with TestingDisableFilter
export TESTING=1
if [[ "$ARGS" == *'--watch'* ]]; then
    ARGS="${ARGS/'--watch'/''}"
    exec poetry run ptw -- $ARGS
else
    exec poetry run pytest $ARGS
fi

