import { path } from "static-path"

export const pathLogin = path("/login")
export const pathSignup = path("/signup")
export const pathPasswordReset = path("/password-reset")
export const pathPasswordConfirm = path("/password-confirm")
export const pathHome = path("/")
// ideally we'd have: path("/t/:id(\d+)(.*)/schedule")
export const pathSchedule = path("/t/:teamId/schedule")
export const pathRecipeAdd = path("/recipes/add")
export const pathRecipesList = path("/recipes/")
// ideally we'd have: path("/recipes/:id(\d+)(.*)")
export const pathRecipeDetail = path("/recipes/:recipeId")
export const pathCookDetail = path("/cook/:recipeId")
export const pathSettings = path("/settings")
export const pathProfileById = path("/profile/:userId")
export const pathPassword = path("/password")
export const pathTeamCreate = path("/t/create")
// ideally we'd have: path("/t/:id(d+)(.*)/invite")
export const pathTeamInvite = path("/t/:teamId/invite")
// ideally we'd have: path("/t/:id(\d+)(.*)/settings")
export const pathTeamSettings = path("/t/:teamId/settings")
// ideally we'd have: path("/t/:id(\d+)(.*)")
export const pathTeamDetail = path("/t/:teamId")
export const pathTeamList = path("/t/")
