#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi

GLOB="\.(js|jsx|scss|css|ts|tsx|json)$"

FILES=$(git diff --name-only master | sed -e "s%frontend/%%"| grep -E "$GLOB")

ARGS="$@"
if [[ $ARGS == *'--list-different'* ]]; then
  $(yarn bin)/prettier "$@" $FILES
else
  $(yarn bin)/prettier --write "$@" $FILES
fi
