#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi

glob="**/*.{js,jsx,scss,css,ts,tsx,json}"

ARGS="$@"
if [[ $ARGS == *'--list-different'* ]]; then
  $(yarn bin)/prettier "$@" "$glob"
else
  $(yarn bin)/prettier --write "$@" "$glob"
fi
