#!/usr/bin/env bash
set -ex

main() {
  if [ "$CI" ]; then
    node_modules/.bin/prettier '**/*.{js,jsx,scss,css,ts,tsx,json,yaml,yml,md}' --list-different
    node_modules/.bin/eslint '**/*.{ts,tsx,js,jsx}'
  else
    node_modules/.bin/prettier '**/*.{js,jsx,scss,css,ts,tsx,json,yaml,yml,md}' --write
    node_modules/.bin/eslint '**/*.{ts,tsx,js,jsx}' --fix
  fi

  node_modules/.bin/tslint --project tsconfig.json --format 'codeFrame'
  node_modules/.bin/tsc --noEmit
}

main "$@"
