#!/usr/bin/env bash
set -ex
set -o pipefail

prettier() {
  if [ "$CI" ]; then
    node_modules/.bin/prettier '**/*.{js,jsx,scss,css,ts,tsx,json,yaml,yml,md}' --list-different | awk -v prefix="$PWD" '{print "formatting-violation:"  prefix "/" $0 ":formatting required"}'
  else
    node_modules/.bin/prettier '**/*.{js,jsx,scss,css,ts,tsx,json,yaml,yml,md}' --write --cache
  fi
}

eslint() {
  if [ "$CI" ]; then
    node_modules/.bin/eslint '**/*.{ts,tsx,js,jsx}'
  else
    node_modules/.bin/eslint '**/*.{ts,tsx,js,jsx}' --fix --cache
  fi
}

tsc() {

  if [ "$CI" ]; then
    # Prefix typescript output to make relative paths absolute paths.
    # 
    # This fixes compatability with actions/setup-node TSC problem matcher, which requires full paths.
    # https://github.com/actions/setup-node/blob/a4fcaaf314b117a40d694a35ee36461f8ff3c6e6/.github/tsc.json
    node_modules/.bin/tsc | awk -v prefix="$PWD" '{print prefix "/" $0}'
  else
    node_modules/.bin/tsc 
  fi
}

main() {
    prettier
    eslint
    tsc
}

main "$@"
