#!/usr/bin/env bash
set -e

cd $(dirname $(dirname "$0"))

if [[ -f ../.env ]]; then
    # export all variables from env file
    set -a
    source ../.env
    set +a
fi

node scripts/lint.js

$(yarn bin)/tslint 'src/**/*.{ts,tsx}' --format 'codeFrame'

$(yarn bin)/tsc --noEmit
