#!/usr/bin/env bash
set -ex

main() {
  export TZ=UTC
  if [ "$CI" ]; then
    node ./frontend/scripts/test.js --env=jsdom --coverage --runInBand
  else
    node ./frontend/scripts/test.js --env=jsdom --watch "$@"
  fi
}

main "$@"
