# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-01 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20171001_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe'),
        ),
    ]
