# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20171116_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='amount',
            new_name='count',
        ),
    ]
