# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0015_auto_20171116_1924")]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="views",
            field=models.IntegerField(default=0, editable=False),
        )
    ]
