# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 05:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0016_recipe_views"), ("core", "0017_recipe_servings")]

    operations = []  # type: ignore
