# Generated by Django 2.0.2 on 2018-03-01 06:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0026_auto_20180301_0442")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="membership",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.Membership",
            ),
        )
    ]
