# Generated by Django 2.0.2 on 2018-03-01 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_invite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='group',
            new_name='level',
        ),
    ]
