# Generated by Django 2.0.2 on 2018-03-03 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0032_auto_20180302_0221")]

    operations = [
        migrations.AddField(
            model_name="membership",
            name="is_active",
            field=models.BooleanField(default=False),
        )
    ]
