# Generated by Django 2.0.2 on 2018-04-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_auto_20180330_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
