# Generated by Django 2.0.2 on 2018-05-10 20:50

from django.db import migrations, models


def set_position(apps, schema_editor):
    """Fill in position for existing records"""
    Step = apps.get_model("core", "Step")
    db_alias = schema_editor.connection.alias
    for step in Step.objects.using(db_alias).all():
        step.position = step.id
        step.save()


class Migration(migrations.Migration):

    dependencies = [("core", "0047_recipe_deleted_at")]

    operations = [
        migrations.AddField(
            model_name="step",
            name="position",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunPython(set_position, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="step", name="position", field=models.FloatField()
        ),
        migrations.AlterUniqueTogether(
            name="step", unique_together={("recipe", "position")}
        ),
        migrations.AlterModelOptions(name="step", options={"ordering": ["-position"]}),
    ]
