# Generated by Django 2.0.2 on 2018-05-11 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_auto_20180510_2050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='deleted_at',
        ),
    ]
