# Generated by Django 2.0.2 on 2018-06-23 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180616_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledrecipe',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Team'),
        ),
    ]
