# Generated by Django 2.0.2 on 2018-06-24 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0058_auto_20180623_2309")]

    operations = [
        migrations.AlterUniqueTogether(
            name="scheduledrecipe", unique_together={("recipe", "on", "user", "team")}
        )
    ]
