# Generated by Django 2.0.2 on 2018-12-23 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("core", "0062_auto_20181223_0449")]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="selected_team",
            field=models.ForeignKey(
                blank=True,
                help_text="team currently focused on UI, null if personal items selected.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.Team",
            ),
        )
    ]
