# Generated by Django 2.0.2 on 2019-01-05 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0065_auto_20190105_1652")]

    operations = [
        migrations.RemoveField(model_name="invite", name="deleted_at"),
        migrations.RemoveField(model_name="membership", name="deleted_at"),
        migrations.RemoveField(model_name="scheduledrecipe", name="deleted_at"),
        migrations.RemoveField(model_name="team", name="deleted_at"),
    ]
