# Generated by Django 2.0.2 on 2019-02-22 23:59

from django.db import migrations

from core.extensions import PgStatStatements


class Migration(migrations.Migration):

    dependencies = [("core", "0066_auto_20190105_1701")]

    operations = [PgStatStatements()]
