# Generated by Django 2.2 on 2019-07-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0068_auto_20190309_2251")]

    operations = [
        migrations.AlterField(
            model_name="scheduledrecipe",
            name="on",
            field=models.DateField(help_text="day when recipe is scheduled"),
        )
    ]
