# Generated by Django 2.2 on 2019-08-24 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_auto_20190730_0312'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ingredient',
        ),
    ]
