# Generated by Django 2.2 on 2019-08-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_delete_ingredient'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Step',
        ),
    ]
