# Generated by Django 2.2 on 2019-11-16 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0071_note"), ("core", "0071_auto_20191101_0111")]

    operations: list = []
