# Generated by Django 2.2 on 2019-08-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_delete_step'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScheduledRecipe',
        ),
    ]
