# Generated by Django 2.2 on 2019-08-24 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_delete_scheduledrecipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recipe',
        ),
    ]
