# Generated by Django 2.2 on 2019-08-24 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_delete_recipe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Invite',
        ),
    ]
