# Generated by Django 2.2.12 on 2020-05-18 02:57

from django.db import migrations, models

import core.models


class Migration(migrations.Migration):

    dependencies = [("core", "0075_auto_20200227_0349")]

    operations = [
        migrations.AddField(
            model_name="team",
            name="ical_id",
            field=models.TextField(
                default=core.models.get_random_ical_id,
                help_text="Secret key used to prevent unauthorized access to schedule calendar.",
            ),
        )
    ]
