# Generated by Django 2.2.12 on 2020-06-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_team_ical_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='foo',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
