# Generated by Django 2.2.12 on 2020-07-15 17:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0076_team_ical_id")]

    operations = [
        migrations.CreateModel(
            name="Section",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="name of the ingredient section group", max_length=255
                    ),
                ),
                (
                    "position",
                    models.FloatField(
                        help_text="position of the section across both the ingredients and other sections for a recipe."
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        help_text="Recipe the section is part of.",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.Recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["position"],
                "unique_together": {("recipe", "position")},
            },
        )
    ]
