# Generated by Django 2.2.12 on 2020-08-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("core", "0077_auto_20200716_0345")]

    operations = [
        migrations.AlterUniqueTogether(name="ingredient", unique_together=set()),
        migrations.RunSQL(
            """
CREATE UNIQUE INDEX core_ingredient_recipe_id_position_not_deleted_uniq_indx
    ON core_ingredient("recipe_id", "position")
    WHERE "deleted_at" IS NOT NULL;
            """
        ),
    ]
