# Generated by Django 2.2.12 on 2020-06-22 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0077_ingredient_foo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='bar',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
