# Generated by Django 2.2.12 on 2020-12-06 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0083_auto_20201206_2146"),
        ("core", "0084_auto_20201126_2226"),
    ]
