# Generated by Django 3.2.9 on 2021-11-18 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0089_backfill_timeline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="recipe",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="section",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shoppinglist",
            name="ingredients",
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name="step",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
        migrations.AlterField(
            model_name="timelineevent",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True, db_index=True, default=None, editable=False, null=True
            ),
        ),
    ]
