# Generated by Django 3.2.9 on 2022-08-05 23:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_upload'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload',
            name='note',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to='core.note'),
        ),
        migrations.AlterField(
            model_name='upload',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='NoteUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.note')),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.upload')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
