# Generated by Django 3.2.9 on 2022-09-19 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0099_auto_20220830_0405"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="position",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="section",
            name="position",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="step",
            name="position",
            field=models.TextField(),
        ),
    ]
