# Generated by Django 3.2.9 on 2022-10-20 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0102_rename_recipe_team_user__deprecated_recipe_team"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="note",
            constraint=models.CheckConstraint(
                check=models.Q(("text__length__gt", 0)), name="minimum_length_required"
            ),
        ),
    ]
