name: UI

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@a09bf677ad5e5dedb31a42070b6a180fde0ab6ce # pin@v4
        with:
          paths: '["frontend/**", ".github/workflows/**"]'
  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Run tests
        working-directory: "frontend"
        run: ./s/test --no-watch --reporter junit --outputFile ~/test-results/frontend_tests.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: test-results
          path: ~/test-results
  format:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Check formatting
        working-directory: "frontend"
        run: ./s/fmt
  eslint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Run Eslint
        working-directory: "frontend"
        run: ./s/eslint
  typecheck:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Check types
        working-directory: "frontend"
        run: ./s/typecheck
  build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Build bundle
        working-directory: "frontend"
        run: ./s/build
  size:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - uses: andresz1/size-limit-action@94bc357df29c36c8f8d50ea497c3e225c3c95d1d # v1.8.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          directory: frontend/
          package_manager: npm
