name: UI

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@c449d86cf33a2a6c7a4193264cc2578e2c3266d4 # pin@v4
        with:
          paths: '["frontend/**", ".github/workflows/**"]'
  test:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Run tests
        working-directory: "frontend"
        run: ./s/test --no-watch --reporter junit --outputFile ~/test-results/frontend_tests.xml
      - name: Archive code coverage results
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: test-results
          path: ~/test-results
  format:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Check formatting
        working-directory: "frontend"
        run: ./s/fmt
  eslint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Run Eslint
        working-directory: "frontend"
        run: ./s/eslint
  typecheck:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Check types
        working-directory: "frontend"
        run: ./s/typecheck
  build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          persist-credentials: false
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: "frontend/package.json"
          cache-dependency-path: "frontend/package-lock.json"
          cache: "npm"
      - name: Install dependencies
        working-directory: "frontend"
        run: npm ci
      - name: Build bundle
        working-directory: "frontend"
        run: ./s/build
