name: VSCode Extension

on:
  pull_request:

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  pre_job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
      paths_result: ${{ steps.skip_check.outputs.paths_result }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@a09bf677ad5e5dedb31a42070b6a180fde0ab6ce # pin@v4
        with:
          paths: '[".vscode/extensions/recipeyak-dev/**", ".github/workflows/**"]'
  format:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v2
        with:
          version: 8
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".vscode/extensions/recipeyak-dev/package.json"
          cache-dependency-path: ".vscode/extensions/recipeyak-dev/pnpm-lock.yaml"
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: pnpm install
      - name: Check formatting
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: ./s/fmt
  eslint:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v2
        with:
          version: 8
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".vscode/extensions/recipeyak-dev/package.json"
          cache-dependency-path: ".vscode/extensions/recipeyak-dev/pnpm-lock.yaml"
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: pnpm install
      - name: Run Eslint
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: ./s/eslint
  typecheck:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v2
        with:
          version: 8
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".vscode/extensions/recipeyak-dev/package.json"
          cache-dependency-path: ".vscode/extensions/recipeyak-dev/pnpm-lock.yaml"
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: pnpm install
      - name: Check types
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: ./s/typecheck
  build:
    needs: pre_job
    if: needs.pre_job.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v3
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v2
        with:
          version: 8
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: ".vscode/extensions/recipeyak-dev/package.json"
          cache-dependency-path: ".vscode/extensions/recipeyak-dev/pnpm-lock.yaml"
          cache: "pnpm"
      - name: Install dependencies
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: pnpm install
      - name: Build bundle
        working-directory: ".vscode/extensions/recipeyak-dev"
        run: ./s/build
